# Obfuscates gacha keys for transport between frontend and backend.
#
# This is NOT a security boundary — it exists only to make casual sniffing/replay of
# GET /api/v1/opponents traffic harder, not to gate content access (anyone with API
# access can still call POST /api/v1/gacha repeatedly). Because of that, both sides
# need to be able to obfuscate/deobfuscate: this uses a shared non-secret salt (not
# Rails' secret_key_base) so the frontend can perform the identical transform in TS.
#
# Scheme: XOR each byte of the key against a deterministic keystream seeded from
# `SALT + timestamp`, generated by a splitmix32 PRNG (pure 32-bit int math, so the
# TS port produces byte-identical output). The timestamp is supplied fresh by the
# caller on every request, so encode/decode always happen with the same timestamp
# within a single round-trip — there is no stale-key rotation to keep in sync.
class GachaCipher
  SALT = "fang-gacha-salt"

  class << self
    # Returns the obfuscated (hex-encoded) key for the given raw key + timestamp.
    def obfuscate(raw_key, timestamp)
      xor_with_keystream(raw_key.b, timestamp.to_i).unpack1("H*")
    end

    # Returns the raw key for the given obfuscated (hex-encoded) key + timestamp.
    def deobfuscate(obfuscated_key, timestamp)
      bytes = [ obfuscated_key ].pack("H*")
      xor_with_keystream(bytes, timestamp.to_i).force_encoding("UTF-8")
    end

    private

    def xor_with_keystream(bytes, timestamp)
      state = seed(timestamp)
      out = bytes.each_byte.map do |byte|
        state = splitmix32(state)
        byte ^ (state & 0xff)
      end
      out.pack("C*")
    end

    def seed(timestamp)
      (SALT + timestamp.to_s).each_byte.reduce(0x811c9dc5) do |acc, byte|
        ((acc ^ byte) * 0x01000193) & 0xffffffff
      end
    end

    def splitmix32(state)
      state = (state + 0x9e3779b9) & 0xffffffff
      z = state
      z = ((z ^ (z >> 16)) * 0x85ebca6b) & 0xffffffff
      z = ((z ^ (z >> 13)) * 0xc2b2ae35) & 0xffffffff
      z ^ (z >> 16)
    end
  end
end
